### ISSUE TITLE
Login list can be lost if Jade crashes

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#47]
Another pretty annoying problem is, that the list of Gemstone-Server (Jade Login) is very often reseted, so that only the default entry is available.

**Comment by feldti** [comment]
Ok, I lost the list of database connection information several times today and here is the way, I was able to make it reproducable:

a) start Jade, define a database connection , login , logout and close the Jade Login window
b) start jade again, you will see your database connection from (a), do a login into Gemstone with that connection
c) get the task manager and kill jade ... goto (a) and you see the default one entry list of database connections, all previous entries are lost

**Comment by jgfoster** [comment]
I've tried the steps you describe and am not able to reproduce the problem. I've tried with Jade 2.4.14 on Windows 10 21H1. Did you see my comment from 19 Feb 2021 and 03 May 2020?

**Comment by feldti** [comment]
Ok, I looked at that file in the userprofile (jade.gss) ... normally the size of this file is around 1KByte. When I terminate Jade (when working in a database by using the task manager), the Jade.gss file has a size of 52 KByte (and contains much more data). After starting Jade again it has at once a size of 1 KByte with the initial one-entry-lis
[JadeData.zip](https://github.com/jgfoster/Jade/files/7579069/JadeData.zip)
t.
