### ISSUE TITLE
Hide Rewrite Tool if Unavailable

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade#51]
Hi James and Bruno,

I don't find any correct source for the needed RB-Classes.

How can I "file In" the correct classes for the "Rewrite Tool" in GEMSTONE 2.4.6 or 3.4.3 ?

Regards
Peter

**Comment by jgfoster** [comment]
I'm going to close this for a couple reasons. First, no further work has been done for almost three years. Second, I think that showing the tab with an explanation of why it isn't available communicates that Jade has some support for this but the server doesn't have the necessary code.
