### ISSUE TITLE
Support for  3.6.2 available ?

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#59]
Hello James, do you have a version for 3.6.2 available ?

**Comment by jgfoster** [comment]
No, I'll try to get that up shortly. Until then you should be able to connect with the 3.6.1 libraries.

**Comment by feldti** [comment]
No, that does not work

**Comment by jgfoster** [comment]
You are right, there seems to be a version incompatibility. I'm preparing a new release now.
