### ISSUE TITLE
Connection failed with a GemStone 3.4.5 server

### ISSUE THREAD

**Issue by jbrichau** [jgfoster/Jade#65]
I am trying to use Jade for connecting to a Gemstone 3.4.5 but I can only select a 3.4.4 in the UI of Jade.
When I am trying using the 3.4.4 gci libs, I get an error.

The netldi log shows:

	accept failed, SSL mismatch: we expect SSL, peer does not expect SSL; client may be using old version of libgci library

Jade says:

<img width="401" alt="Screenshot 2022-02-18 at 23 28 30" src="https://user-images.githubusercontent.com/933094/154775203-eb1bdced-1a20-4c9b-bb78-a4c33ad213b5.png">

Can I use Jade to connect to a GemStone 3.4.5 ?

On the glass mailinglist, Martin confirmed he could connect fine. https://lists.gemtalksystems.com/mailman/archives/glass/2022-February/006486.html 

What can I do to see where the problem is?

**Comment by jgfoster** [comment]
I've created version [2.4.21](https://github.com/jgfoster/Jade/releases/tag/2.4.21) with explicit support for 3.4.5. As Martin notes, other libraries probably would work so it is likely that there are additional problems.
