### ISSUE TITLE
Jade 2.4.21 - Compiling a method throws an error

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#67]
Compiling a method in the class browser, but if you search for am implementor of a specific method, a special browser get opened with that method - and if someone wants to recompile that method an exception is thrown in:

JadeServer64bit34>>compileMethod:behaviour: symbolList:inCategory

at line 27:

.... method key selector ....

and method is an instance of GsNMethod and instances of this class do **not** understand "key".

**Comment by feldti** [comment]
Compiling a method in the class browser works ...

**Comment by jgfoster** [comment]
With Jade 2.4.24 connected to 3.6.6 I'm able to recompile a method in the Method Browser.
