### ISSUE TITLE
Running Jade on OS X 10.15.7

### ISSUE THREAD

**Issue by spar65** [jgfoster/Jade#69]
James,

New to the community, trying to learn SmallTalk and GS for a project I am working on. Would love to use your Jade tool. Any recommendations for getting to run on my OS X install of Catalina 10.15.7? (Wine will not work since I am in 64 bit.)

Thanks for your help!
Greg Spehar
503-332-3663

**Comment by spar65** [comment]
Hi James,

I was able to load Fusion and then Windows 10, and was able to load Jade. My Gemstone Stone is running on my Apple instance and for some reason I am not able to login. I have an error called Unknown GciLoginFailed has Occured. I am working through the video but seem to be stuck here. Will continue to try but I am open to other suggestions... I have 
![Spehar-Login-Jade](https://user-images.githubusercontent.com/109361506/226068442-6bde7850-a47d-469b-b7aa-710444987873.PNG)

**Comment by jgfoster** [comment]
A common problem is with hostname and service lookup on the Windows VM. I see that you have the NetLDI as a port rather than a name, so that is good. When you use `ping` and the hostname, does it resolve? Then you need to make sure that your NetLDI is actually listening on port 50377. The best way to check that is `gslist -cvl` in a macOS terminal. Also, I see that you have set a Stone Host. Note that this is the address of the stone _from the perspective of the Gem_ (not from Jade). So it is almost always best to just leave it as `localhost`. Let me know how that goes...

**Comment by jgfoster** [comment]
And it appears that I didn't respond to your initial inquiry six months ago. I apologize for that; I'm usually more proactive about encouraging interest in GemStone and Jade and Smalltalk (note the capitalization). Welcome!

Also, as long as you are using macOS, you may want to have a look at my [Cocoa application](https://github.com/jgfoster/GemStoneApp) to manage GemStone.

**Comment by spar65** [comment]
Good Morning James, thanks for replying! I am working to proceed with the Application I am hoping to build. I have more confidence that I can do it now that I have ChatGPT, I will send over an example of my Business Requirements once I have put them together. (It has solved sooooo many questions and was incredibly helpful.) My hope is to complete a Prototype and then see if I can get a couple of clients. I have been able to prove that I will be able to integrate GemStone Smalltalk with Flutter, Aragon DAO SDK and PayPal integration. It looks more straight forward than I thought and I have the object model setup.

My only blocker now is to get Jade working with my stone so that  I can prototype my Objects.

Here is the ping you asked about. and the GSLIST. I have also changed the GemHost to LocalHost
![Ping My MacBook](https://user-images.githubusercontent.com/109361506/226111276-0cff9ee9-9c2e-4802-a873-a7d966cfdcea.PNG)
![GSList-CvL](https://user-images.githubusercontent.com/109361506/226111281-e4f3ac32-3fe9-4cf0-99a0-260cfe82ce08.png)

**Comment by spar65** [comment]
![Spehar-Login-Jade-Shapshot-2](https://user-images.githubusercontent.com/109361506/226111351-0704f802-8248-4d4a-821d-23d3a28907cc.PNG)

Here is my Screenshot #2 of Jade.

**Comment by spar65** [comment]
Same error

**Comment by spar65** [comment]
I have been using the GemStone App on MacOS. I might have messed up my installation, it seems to be confused and thinks there is a GemStone stene gs64stone and gs64stone1. (And I seem to have a netldi1 as well.) Once I clear everything from the command line... it shows stone and stone1 as killed and netldi as exists. I then used the GemStone App on OSX and the startup failed. Then I tried to do it from the command line. As you can see there is an issue with my repository log. Should I uninstall everything and start over?

Thanks

![GemStone1](https://user-images.githubusercontent.com/109361506/226113342-1b3b7a66-c6a1-496f-b3a3-b5c4495e23ee.png)
![GemStone 2](https://user-images.githubusercontent.com/109361506/226113346-b3ad2c9a-577b-47b8-9978-ea99bfb2c51f.png)
![Gemstone 3](https://user-images.githubusercontent.com/109361506/226113348-f839e399-8f7a-426d-8063-4fef32869c86.png)

**Comment by spar65** [comment]
It strange but from a different Shell I am able to start and stop everything, but with a different path...
![Gemstone 4](https://user-images.githubusercontent.com/109361506/226113511-3a813478-fecf-48d2-a2c5-2b8ace500546.png)

**Comment by jgfoster** [comment]
Try `gslist -cvl` to cleanup killed processes and verify the existing ones. I don't think that will solve everything, but it will give us more information. Another possible issue is firewalls in Windows preventing outbound calls and in macOS preventing inbound calls. Also a concern can be for now Fusion is configured for networking (bridge, shared, private, etc.).

**Comment by spar65** [comment]
Ok, here is a screen shot of the gslist -cvl... worked for both shell scripts. I have also disabled the firewall for my Mac and for the Windows Installation. Is there a setting for Fusion I should check? Additionally, I noticed that in the Login, it will not let me choose 3.6.5. The login disapears. But when I try to use 3.5.2 it has an active login button... Both are added here...

![GSList-3-18-2023](https://user-images.githubusercontent.com/109361506/226131100-c50a3030-27af-4ed3-bea9-cdf73dfe2a98.png)
![Jade-Login-3 5 2](https://user-images.githubusercontent.com/109361506/226131263-212131bb-dff6-46e2-b42c-5ed9d177840c.PNG)

![Jade-Login-3 6 5](https://user-images.githubusercontent.com/109361506/226131256-6f947baf-6069-46f6-b1f2-85e5773f2099.PNG)

**Comment by spar65** [comment]
James, I will uninstall all of the 3.6.5 instances and just hold on to the dmg file as backup. I will download and work through the installation guide for 3.7.0, then I will give it a try. (I am thinking that I might not have setup the extent properly with the right permissions. (Maybe the GCI issue will clear up as well.) Please give me a week or two to get this done, have a big project at work I need to focus on at the moment.

**Comment by spar65** [comment]
James... Reloaded the GemStone system and ran step by step through the Installation. But still having issues, I realized that maybe I have an issue with the installation in general, so I tried to login to the Stone with Topaz. (NOTE: I did update the file called installtimezone.txt and updated it to Americas/Chicago, so it should work. I shut down the Stone and restarted it. (do I need to do something with that file?) Also, in my install script I did it under Root and accepted all the standard questions.

Here is the list for the topaz login attempt. Note the error at the end...

Gregs-MacBook-Pro-2:upgrade spehargreg$ topaz
[Info]: Loaded /Users/spehargreg/Development/GemStone64Bit3.6.5-i386.Darwin/lib/libgcirpc-3.6.5-64.dylib
 ________________________________________________________________________________
|              GemStone/S64 Object-Oriented Data Management System               |
|                    Copyright (C) GemTalk Systems 1986-2022                     |
|                              All rights reserved.                              |
+--------------------------------------------------------------------------------+
|    PROGRAM: topaz, Linear GemStone Interface (Remote Session)                  |
|    VERSION: 3.6.5, Thu Jul 21 12:41:02 2022 (branch 3.6.5)                     |
|     COMMIT: 2022-07-21T12:29:13-07:00 81403d45c10b5d1be876e33d0d4d23cfc58aec8f |
|  BUILT FOR: Darwin (macOS)                                                     |
| RUNNING ON: 8-CPU Gregs-MacBook-Pro-2.local x86_64 (Darwin 19.6.0 )            |
|  PROCESSOR: 4-core Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (Ivy Bridge)      |
|     MEMORY: 16384 MB                                                           |
| PROCESS ID: 27337     DATE: 03/21/2023 13:40:34 CDT                            |
|   USER IDS: REAL=spehargreg (501) EFFECTIVE=spehargreg (501) LOGIN=root (0)    |
|________________________________________________________________________________|
neither .topazini nor $HOME/.topazini were found
topaz> set gemstone gs64stone
topaz> set username DataCurator
topaz> set password swordfish
topaz> login
-----------------------------------------------------
GemStone: Error         Fatal

Error Category: 231169 [GemStone] Number: 4042 NetLDI service 'gs64ldi' on node '::1' port 50377, not found, connect(4,127.0.0.1,port=50377) failed with errno=22,EINVAL, Invalid argument (programmer error) Arg Count: 0 Context : 20 exception : 20

**Comment by jgfoster** [comment]
This error looks like netldi is not running. What do you get from `gslist -cvl`?

It has been a long time since I installed GemStone following the official instructions. While accurate and complete, they do allow for more options and complexity than you need. Since you are using macOS, I recommend you remove everything and use GemStone App (referenced earlier) to do the install and run.

I'd really like to get this working for you (and find out what isn't working). I'm particularly interested in your plans for Flutter (I'm using it for a front-end for a [WebGS](https://github.com/jgfoster/WebGS) backend).

**Comment by spar65** [comment]
James, thanks for the pointers. Looks like I needed to start over and fully utilize your GemStoneApp. Once I cleared that up I was able to identify how I was able to use Jade in Window. It works great now! Thanks a million. (Nice job on these apps and the GSWeb, they are fantastic!)
