### ISSUE TITLE
Is it possible to disable the JADE's encoding/encrpytion for messaging?

### ISSUE THREAD

**Issue by mmaxus35** [jgfoster/Jade#70]
Is it possible to disable the JADE's encoding/encrpytion for messaging and have a monitoriable content using any third party and platform-independent framework to observe the message traffic between agest?

Thanks.

**Comment by jgfoster** [comment]
Jade makes calls to a DLL distributed by GemTalk Systems LLC for use with GemStone (see [here](https://gemtalksystems.com/products/gs64/versions36x/) for the Windows client download). For information about the wire protocol between the DLL and the server, you would need to ask GemTalk (perhaps on one of their [mailing lists](https://gemtalksystems.com/techsupport/community-and-mailing-lists/)). 

If you say more about what you want to accomplish, I might be able to give more advice.
