### ISSUE TITLE
Error when saving the source code of a method

### ISSUE THREAD

**Issue by tcleenewerck** [jgfoster/Jade#72]
I'm using the latest release of jade (version 2.4.25 Dolphin 7.1.24-10...) with gemstone 3.4.5 on windows. When I save a method (alter its source code) i get the following exception: https://share.getcloudapp.com/kpul4Xeo

**Comment by feldti** [comment]
Me (with 2.4.26)  too, the reason is, that you do it in a MethodList Browser ...

**Comment by jgfoster** [comment]
Actually, while it is related to the MethodListBrowser, it also depends on your repository contains a method `(Behavior includesSelector: #'compileMethod:category:using:environmentId:')`. I have a fix for this.

**Comment by jgfoster** [comment]
Fixed by 4f2ee7d.
