### ISSUE TITLE
Jade 2.4.24 - Inspector does not show content of instances of Time (SmallTime ?)

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#73]
I assume, they are instances of SmallTime

**Comment by feldti** [comment]
Time now shows an empty inspector - also in 2.4.26

**Comment by jgfoster** [comment]
Yes, this is one of the new specials that Jade didn't handle. This is an easy fix...

**Comment by jgfoster** [comment]
Fixed by 4f2ee7d.
