### ISSUE TITLE
Jade 2.4.26, GS 3.7.0 - session lost ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#76]
Well, I also noticed this ... connect to GS 3.7.0, do nothing for some time and I very often get "lost session"

**Comment by feldti** [comment]
Ok, that was an easy one ... the community edition free license was the reason for that.

**Comment by jgfoster** [comment]
A lost session should not have anything to do with the license. Was there anything in the logs (stone and gem)?
