### ISSUE TITLE
Can not create a new Jade Login ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#79]
Today (!) I got a new error - somehow my jade login list has been resetted to one entry ... and I press "+" to get a new entry and that did not work and I got an error.

The reason is simple:

Under JadeLoginShell>addLogin one can see:

login := loginListPresenter selectionOrNil 
		ifNil: [JadeLogin default]
		ifNotNil: [:value | value copy].

and this "copy" set the lastLogin attribute to nil JadeLogin>>postCopy, BUT further in that method:

 (loginListPresenter list copyWith: login)

is executed and the list is an instance of SortedCollection and the sort is done over "lastLogin" and you get it ? The newly added JadeLogin-instance has no value at that attribute. Its nil and it crashed.

**Comment by feldti** [comment]
Ok, I could fixed it here ... but I do not understand, why it popped up now ... all very strange. I used this very for quite some time. But I fixed it here now

**Comment by jgfoster** [comment]
This still should be investigated and fixed in the main branch. If you submit a pull request I can merge it or I can work with the code you provided in your initial report.

**Comment by jgfoster** [comment]
`JadeLoginShell>>loadDataFrom:` sets the list to an `OrderedCollection` and it is only when you click on the 'Last Login' column heading that the GUI tries to sort and gets the error. I'll update the sort block to handle nil. As a work-around, you can avoid the problem by clicking on another column before adding a new login.

**Comment by jgfoster** [comment]
Fixed by 4f2ee7d.
