### ISSUE TITLE
How can I create a new Jade.exe from the development image ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#80]
Are there any instructions how to produce a new executable from a development 7.1.x image

**Comment by jgfoster** [comment]
Select the 'Jade Deployment' package, bring up the context menu (right-click), select 'Deployment', select 'Deploy Executable...', and click 'Deploy' (or click 'Next' to see/change the default options).
![Screenshot 2023-12-12 at 9 29 43 AM](https://github.com/jgfoster/Jade/assets/1577872/be398611-f669-469d-9a0c-455e2bc0829e)

**Comment by feldti** [comment]
Ahh, worked and I got a new Jade environment. Thanks
