### ISSUE TITLE
Jade and invalid Gemstone/S sessions

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade#83]
For some time now I'm facing the problem, that Jade has to be terminated, because the Gemstoner/S session is invalid - and I do not know why this happened (well it happened when I leave Jade alone for some amount of time, doing nothing and then come back to do some work). Currently I face the problem with Gemstone 3.7.0 and Jade 2.4.28 (but it happened with earlier versions also).

**Comment by jgfoster** [comment]
Do you have a walkback? If there is a MessageBox you may be able to generate one by holding down the shift key when pressing Ok. You mention "invalid GemStone/S sessions". Is that part of an error dialog? Are there other users logged in during this time generating commit records? If you select the "Jade/Sleep and Commit" menu command does that prevent the problem?

**Comment by jgfoster** [comment]
Sorry I couldn't reproduce this. Feel free to reopen this with more details.
