### ISSUE TITLE
GS 3.7.1 login failed

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade#84]
Should a login to GS 3.7.1 work already.
Error -> An unknown GciLoginFailed has occured.

Ther are no log entries on the server side.
And there is no specific libarary for 3.7.1 in the /jade/bin directory at least.

**Comment by jgfoster** [comment]
I've had the 3.7.0 libraries work fine for 3.7.1 but I'll create a new version with 3.7.1 libraries. In any case, it is unlikely that this will fix the error which is most likely a failure to communicate with the NetLDI on the IP:port provided.

**Comment by obi068** [comment]
Sorry the netldi was not running with the correct parameters.
We did the upgradeImage from 3.6.1 to 3.7.1 only.
BTW: Login with an empty extent does work.

But we still can't login with the upgraded 3.7.1 Database:
-> GciSession33 does not unterstand #_isLarge
is the error message if we want to login

**Comment by jgfoster** [comment]
I've tried upgrading an image from 3.6.1 to 3.7.1 and did not get any errors on login. Do you get a walkback? If you get a dialog with the error, hold down the shift key and press Ok. This should generate an error log next to the executable. With that we may get a better idea of what is in your image that is sending that message.

**Comment by obi068** [comment]
Error log is attached!
[Jade_ERRORS.txt](https://github.com/user-attachments/files/16328112/Jade_ERRORS.txt)

**Comment by jgfoster** [comment]
I believe that this is fixed. The problem was an interaction between a ClientForwarder (used in Jade for the Transcript and for simple messages/prompts) and SessionTemps.
